name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./calling-service-context/pom.xml
          mvn clean package -f ./driver-service-context/pom.xml
          mvn clean package -f ./customer-service-context/pom.xml

      - name: Docker Build and push for CallingServiceContext
        uses: docker/build-push-action@v4
        with:
          context: ./calling-service-context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/calling-service-context:latest
            ghcr.io/${{ github.repository }}/calling-service-context:${{ github.ref_name }}
            
      - name: Docker Build and push for DriverServiceContext
        uses: docker/build-push-action@v4
        with:
          context: ./driver-service-context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/driver-service-context:latest
            ghcr.io/${{ github.repository }}/driver-service-context:${{ github.ref_name }}
            
      - name: Docker Build and push for CustomerServiceContext
        uses: docker/build-push-action@v4
        with:
          context: ./customer-service-context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer-service-context:latest
            ghcr.io/${{ github.repository }}/customer-service-context:${{ github.ref_name }}
            
